/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'agorjux' at '18/11/15 11:56' with Gradle 2.6
 *
 * @author agorjux, @date 18/11/15 11:56
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
